// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxjbUKeR1Cw9118ZNA3pFypbR9jIWoqGM',
    appId: '1:38752546690:web:0570f703595446f58e699b',
    messagingSenderId: '38752546690',
    projectId: 'diet-hut',
    authDomain: 'diet-hut.firebaseapp.com',
    storageBucket: 'diet-hut.appspot.com',
    measurementId: 'G-QT1NHC01W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpGV_YOzj_LxP4dyfQ8yron8YSugrHoE',
    appId: '1:38752546690:android:d7629fee639bee9c8e699b',
    messagingSenderId: '38752546690',
    projectId: 'diet-hut',
    storageBucket: 'diet-hut.appspot.com',
  );
}
